#!/bin/sh
# This script will compile SchoolCountdown into .class files and then run it.

printf "Compiling SchoolCountdown... "
javac SchoolCountdown.java
printf "Finished Compiling.\n"
printf "Running program..."
java SchoolCountdown
